name: barber_agenda
description: "Aplicación para agendar citas en barberías"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.1.3

  # State Management
  provider: ^6.1.2

  # Utilidades
  intl: ^0.18.1

  # ✅ AGREGAR ESTA:
  url_launcher: ^6.3.1

  #calendar
  table_calendar: ^3.0.9

  # UI
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/barber_icon.png"
  adaptive_icon_background: "#1A1A2E"
  adaptive_icon_foreground: "assets/icon/barber_icon_foreground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icon/icon_google.png